<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>0.2.0</Version>
    <Authors>PSVR2 iRacing Haptics contributors</Authors>
    <Product>PSVR2 iRacing Haptics</Product>
  </PropertyGroup>
</Project>
