<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PSVR2iRacingHaptics.Core\PSVR2iRacingHaptics.Core.csproj" />
    <ProjectReference Include="..\..\src\PSVR2iRacingHaptics.Infrastructure\PSVR2iRacingHaptics.Infrastructure.csproj" />
  </ItemGroup>
</Project>
